### ISSUE TITLE
vimtouch doesn't accept new file name after "save as"

### ISSUE THREAD

**Issue by nnako** [momodalo/vimtouch#94]
After loading a text file onto the screen and editing it, **`:w`** writes the text into the original file. That's fine. Attempting to save the text with an other file name using **`:w <newname>`** works for new files as well. But doing the latter, the current file name does not Change. So subsequent usages of **`:w`** will save the text into the _old_ file again.

Is this a BUG or just a usage mistake on my side? How can I assign a new file name to my buffer in order to be able to use the normal write command **`:w`** to keep its new file name?

**Comment by rafaeln** [comment]
I think this is vim. If I want to save a file with a new name, I use
:sav <newname>. But I haven't actually checked desktop vim to be sure.

**Comment by nnako** [comment]
thanks. You have been right. **`:sav <newname>`** saves the current buffer into a new file. A subsequent use of **`:w`** uses the new file as the target to feed in the buffer contents.
